[build]
publish = "dist"

[[plugins]]
package = "@netlify/plugin-sitemap"
  [plugins.inputs]
  changeFreq = "weekly"
  priority = 0.5

[[plugins]]
package = "netlify-plugin-submit-sitemap"
  [plugins.inputs]
  providers = ["google", "bing", "yandex"]